export type PortfolioProject = {
  id: string;
  title: string;
  client: string;
  country: string;
  region: string;
  year: number;
  service: "organizational-strengthening" | "capacity-strengthening" | "system-strengthening" | "safety-security";
  thematic?: string;
  description: string;
  tags?: string[];
  donor?: string;
};

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
  // ── ORGANIZATIONAL STRENGTHENING ──────────────────────────────────
  {
    id: "wfp-kenya-strategic-plan",
    title: "WFP Kenya Country Strategic Plan 2022–2026",
    client: "WFP",
    country: "Kenya",
    region: "East Africa",
    year: 2021,
    service: "organizational-strengthening",
    thematic: "food-security",
    description: "Led development of the WFP Kenya Country Strategic Plan 2022–2026 as Technical Lead for Evaluation & Learning, incorporating zero hunger, nutrition, climate resilience, and gender-transformative frameworks aligned with national food security goals.",
    tags: ["Strategic Planning", "Food Security", "WFP", "Kenya"],
    donor: "WFP",
  },
  {
    id: "irc-global-strategy",
    title: "IRC Global Strategy 2020–2024",
    client: "IRC",
    country: "Multi-Country (41)",
    region: "Global",
    year: 2019,
    service: "organizational-strengthening",
    thematic: "governance",
    description: "Core team member for IRC's 41-country global strategy development, driving organisational alignment, theory of change architecture, and outcome framework design across humanitarian and development contexts in Africa, Asia, Middle East, and Latin America.",
    tags: ["Strategic Planning", "Governance", "IRC", "Global"],
    donor: "IRC",
  },
  {
    id: "usaid-deai-strategy",
    title: "USAID Eastern Africa Diversity, Equity, Accountability & Inclusion Strategy",
    client: "USAID",
    country: "Multi-Country (6)",
    region: "East Africa",
    year: 2024,
    service: "organizational-strengthening",
    thematic: "gender",
    description: "Team Leader for development of USAID Eastern Africa's DEAI Strategy, setting a regional framework for inclusive programming and workforce practices across Kenya, Uganda, Tanzania, Ethiopia, Rwanda, and Burundi.",
    tags: ["Strategic Planning", "Gender", "Inclusion", "USAID", "East Africa"],
    donor: "USAID",
  },
  {
    id: "usaid-rdcs-eastern-africa",
    title: "USAID Regional Development Cooperation Strategy — Eastern Africa",
    client: "USAID",
    country: "Multi-Country (6)",
    region: "East Africa",
    year: 2021,
    service: "organizational-strengthening",
    thematic: "governance",
    description: "M&E and Learning Specialist for USAID's RDCS and CDCS across Kenya, Uganda, Tanzania, Ethiopia, Rwanda, and Burundi.",
    tags: ["Strategic Planning", "USAID", "East Africa", "MEL"],
    donor: "USAID",
  },
  {
    id: "eac-food-security",
    title: "EAC Food Security Action Plan II (2017–2021)",
    client: "East African Community",
    country: "Multi-Country (6)",
    region: "East Africa",
    year: 2017,
    service: "organizational-strengthening",
    thematic: "food-security",
    description: "Team Lead for development of the EAC Food Security Action Plan II covering Kenya, Uganda, Tanzania, Rwanda, Ethiopia, and South Sudan, addressing regional food systems, cross-border trade, and climate resilience.",
    tags: ["Strategic Planning", "Food Security", "EAC", "Regional"],
    donor: "EAC",
  },
  {
    id: "cbm-kenya-country-strategy",
    title: "CBM Kenya Country Community Support Services Strategy",
    client: "CBM",
    country: "Kenya",
    region: "East Africa",
    year: 2023,
    service: "organizational-strengthening",
    thematic: "health",
    description: "Team Lead for situational analysis and development of CBM Kenya's Country Community Support Services Strategy, informing disability-inclusive development and eye health programming priorities.",
    tags: ["Strategic Planning", "Disability", "Eye Health", "CBM", "Kenya"],
    donor: "CBM",
  },
  {
    id: "amref-icd-strategy-mtr",
    title: "Amref Health Africa ICD Strategy Mid-Term Review",
    client: "Amref Health Africa",
    country: "Multi-Country (10)",
    region: "Africa",
    year: 2021,
    service: "organizational-strengthening",
    thematic: "health",
    description: "Team Lead for mid-term review of Amref Health Africa's Institute of Capacity Development Strategy across Kenya, Uganda, Tanzania, Malawi, Zambia, Ethiopia, Senegal, Côte d'Ivoire, South Sudan, and South Africa.",
    tags: ["Evaluation", "Capacity Development", "Amref", "Africa"],
    donor: "Amref Health Africa",
  },
  // ── CAPACITY STRENGTHENING ────────────────────────────────────────
  {
    id: "unicef-moh-mental-health",
    title: "UNICEF/MoH Kenya Mental Health Integration Handbook",
    client: "UNICEF",
    country: "Kenya",
    region: "East Africa",
    year: 2024,
    service: "capacity-strengthening",
    thematic: "health",
    description: "Team Leader for development of the national handbook for integrating mental health into the Ministry of Health's continuum of care for ANC, MCH, and PNC services targeting pregnant adolescent girls.",
    tags: ["Capacity Building", "Mental Health", "UNICEF", "Kenya", "SRHR"],
    donor: "UNICEF",
  },
  {
    id: "amref-annual-technical-report-2021",
    title: "Amref Health Africa Annual Technical Report",
    client: "Amref Health Africa",
    country: "Multi-Country (10)",
    region: "Africa",
    year: 2021,
    service: "capacity-strengthening",
    thematic: "health",
    description: "Team Lead for development of Amref Health Africa's annual technical report synthesising programme results across Kenya, Uganda, Tanzania, Malawi, Zambia, Ethiopia, Senegal, Côte d'Ivoire, South Sudan, and South Africa.",
    tags: ["Reporting", "Health Systems", "Amref", "Multi-Country"],
    donor: "Amref Health Africa",
  },
  {
    id: "amref-covid-lessons-2022",
    title: "Amref Health Africa COVID-19 Pandemic Lessons Documentation",
    client: "Amref Health Africa",
    country: "Multi-Country (8)",
    region: "Africa",
    year: 2022,
    service: "capacity-strengthening",
    thematic: "health",
    description: "Team Lead for cross-country documentation of lessons learned from Amref Health Africa's COVID-19 pandemic response across Kenya, Uganda, Tanzania, Malawi, Ethiopia, Senegal, South Sudan, and European offices.",
    tags: ["Lessons Learned", "COVID-19", "Health", "Amref", "Africa"],
    donor: "Amref Health Africa",
  },
  // ── SYSTEM STRENGTHENING ──────────────────────────────────────────
  {
    id: "fairtrade-mel-ecosystem",
    title: "Fairtrade Africa MEL Ecosystem — Phase I & II",
    client: "Fairtrade Africa",
    country: "Multi-Country (12)",
    region: "Africa",
    year: 2021,
    service: "system-strengthening",
    thematic: "food-security",
    description: "Team Lead for design and rollout of a continental MEL ecosystem for Fairtrade Africa across 12 countries, including KoBoToolbox digital data collection tools and live performance dashboards.",
    tags: ["MEL Systems", "Data Management", "Fairtrade", "Africa"],
    donor: "Fairtrade Africa",
  },
  {
    id: "fairtrade-mel-ecosystem-phase3",
    title: "Fairtrade Africa MEL Ecosystem — Phase III Digital Alignment",
    client: "Fairtrade Africa",
    country: "Multi-Country (12)",
    region: "Africa",
    year: 2022,
    service: "system-strengthening",
    thematic: "food-security",
    description: "Team Lead for Phase III development and alignment of Fairtrade Africa's digital data management system, integrating producer-level data flows into a unified continental MEL architecture across 12 African countries.",
    tags: ["MEL Systems", "Digital Systems", "Fairtrade", "Africa"],
    donor: "Fairtrade Africa",
  },
  {
    id: "fairtrade-africa-mtr",
    title: "Fairtrade Africa 2021–2025 Strategic Plan Mid-Term Review",
    client: "Fairtrade Africa",
    country: "Multi-Country (12)",
    region: "Africa",
    year: 2023,
    service: "system-strengthening",
    thematic: "food-security",
    description: "Team Leader for mid-term review of Fairtrade Africa's 2021–2025 Strategic Plan across 12 African countries, assessing smallholder farmer livelihood outcomes, gender integration, and organisational effectiveness.",
    tags: ["Evaluation", "Food Security", "Fairtrade", "Multi-Country"],
    donor: "Fairtrade Africa",
  },
  {
    id: "fairtrade-covid-impact-eval",
    title: "Fairtrade Africa COVID-19 Funding Impact Evaluation",
    client: "Fairtrade Africa",
    country: "Multi-Country (12)",
    region: "Africa",
    year: 2021,
    service: "system-strengthening",
    thematic: "food-security",
    description: "Team Lead for impact evaluation of COVID-19 emergency funding for Fairtrade Africa producer organisations across 12 countries, assessing economic resilience, food security, and smallholder farmer recovery.",
    tags: ["Impact Evaluation", "COVID-19", "Food Security", "Fairtrade", "Africa"],
    donor: "Fairtrade Africa",
  },
  {
    id: "recover-africa-mel",
    title: "RECOVER Africa M&E Systems — Fairtrade International",
    client: "Fairtrade International",
    country: "Multi-Country (12)",
    region: "Africa",
    year: 2020,
    service: "system-strengthening",
    thematic: "food-security",
    description: "MEL Advisor for design and implementation of Africa-wide M&E systems for the RECOVER Africa COVID-19 economic recovery project across Fairtrade producer organisations in 12 countries.",
    tags: ["MEL Systems", "COVID-19", "Resilience", "Fairtrade", "Africa"],
    donor: "Fairtrade International",
  },
  {
    id: "undp-kenya-devolution-mtr",
    title: "UNDP/UN Women/UNICEF Kenya Joint Devolution Programme MTR",
    client: "UNDP",
    country: "Kenya",
    region: "East Africa",
    year: 2022,
    service: "system-strengthening",
    thematic: "governance",
    description: "Evaluation Expert for the mid-term review of the joint UNDP/UN Women/UNICEF Kenya devolution programme, assessing county-level governance, gender equity, and social protection outcomes across 47 counties.",
    tags: ["Evaluation", "Governance", "Gender", "UNDP", "Kenya"],
    donor: "UNDP",
  },
  {
    id: "dutch-mofa-drc",
    title: "Dutch MOFA Civil Society Policy Framework DQA — DRC",
    client: "Dutch Ministry of Foreign Affairs",
    country: "DRC",
    region: "Central Africa",
    year: 2024,
    service: "system-strengthening",
    thematic: "governance",
    description: "Team Lead for data quality assessment (DQA) and third-party monitoring of the Strengthening Civil Society Policy Framework funded by the Dutch Ministry of Foreign Affairs in the Democratic Republic of Congo.",
    tags: ["DQA", "Third-Party Monitoring", "Civil Society", "DRC"],
    donor: "Dutch Ministry of Foreign Affairs",
  },
  {
    id: "sida-somalia-resilience",
    title: "SIDA Somalia Resilience Programme End-Term Review",
    client: "Swedish Development Corporation",
    country: "Somalia",
    region: "Horn of Africa",
    year: 2023,
    service: "system-strengthening",
    thematic: "food-security",
    description: "Team Lead for end-term evaluation of SIDA's Somalia Resilience Programme, examining food security, livelihoods, value chains, emergency response, health, education, and women's empowerment outcomes.",
    tags: ["Evaluation", "Resilience", "Food Security", "SIDA", "Somalia"],
    donor: "SIDA",
  },
  {
    id: "amref-kenya-sp-baseline-2023",
    title: "Amref Health Africa Kenya Strategic Plan Baseline Assessment 2023–2030",
    client: "Amref Health Africa",
    country: "Kenya",
    region: "East Africa",
    year: 2023,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for baseline assessment for Amref Health Africa Kenya's 2023–2030 Strategic Plan, establishing indicator benchmarks across community health, reproductive health, and health systems strengthening domains.",
    tags: ["Baseline", "Health Systems", "Amref", "Kenya"],
    donor: "Amref Health Africa",
  },
  {
    id: "world-bank-kusp-vfm",
    title: "Kenya Urban Roads Programme Value for Money Assessment",
    client: "World Bank",
    country: "Kenya",
    region: "East Africa",
    year: 2023,
    service: "system-strengthening",
    thematic: "governance",
    description: "Statistician for VfM assessment of the Kenya Urban Roads Programme (KUSP) for the World Bank and Kenya Ministry of Lands, analysing cost-effectiveness and development impact of urban road infrastructure investments.",
    tags: ["Value for Money", "Infrastructure", "World Bank", "Kenya"],
    donor: "World Bank",
  },
  {
    id: "amref-power-to-youth-mtr",
    title: "Amref Power to You(th) Programme Mid-Term Evaluation",
    client: "Amref Netherlands",
    country: "Multi-Country (7)",
    region: "Africa",
    year: 2022,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for mid-term evaluation of the Power to You(th) Programme across Ethiopia, Kenya, Uganda, Malawi, Ghana, Senegal, and Indonesia, assessing adolescent SRHR, mental health, and youth empowerment outcomes.",
    tags: ["Evaluation", "Youth", "SRHR", "Amref", "Multi-Country"],
    donor: "Amref Netherlands",
  },
  {
    id: "dfpa-srh-baseline-east-africa",
    title: "Danish FPA Sexual & Reproductive Health Baseline — East Africa",
    client: "Danish Family Planning Association",
    country: "Multi-Country (3)",
    region: "East Africa",
    year: 2022,
    service: "system-strengthening",
    thematic: "health",
    description: "Team member for baseline study on Sexual and Reproductive Health Rights across Ethiopia, Kenya, and Uganda, establishing metrics for family planning access, SRHR knowledge, and gender equity indicators.",
    tags: ["Baseline", "SRHR", "Family Planning", "East Africa"],
    donor: "Danish Family Planning Association",
  },
  {
    id: "save-children-kenya-pneumonia",
    title: "Save the Children Kenya Pneumonia Urban Slums End-Line Evaluation",
    client: "Save the Children International",
    country: "Kenya",
    region: "East Africa",
    year: 2022,
    service: "system-strengthening",
    thematic: "health",
    description: "Principal Investigator for end-line evaluation of the Kenya pneumonia in urban slums of Nairobi project, assessing reductions in childhood pneumonia morbidity and mortality through community health interventions.",
    tags: ["Evaluation", "Child Health", "Urban Health", "Kenya"],
    donor: "Save the Children",
  },
  {
    id: "unicef-kenya-nutrition-2021",
    title: "UNICEF Kenya Nutrition & Sanitation Programme End Point Revision",
    client: "UNICEF",
    country: "Kenya",
    region: "East Africa",
    year: 2021,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for end point revision of Kenya's Nutrition and Sanitation Programme and development of a national scale-up roadmap, informing the government's investment framework for nutrition-sensitive interventions.",
    tags: ["Evaluation", "Nutrition", "WASH", "UNICEF", "Kenya"],
    donor: "UNICEF",
  },
  {
    id: "save-children-kenya-health-signature",
    title: "Save the Children Kenya Health Signature Project End-Term Evaluation",
    client: "Save the Children",
    country: "Kenya",
    region: "East Africa",
    year: 2021,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for end-of-term evaluation of the Kenya Health Signature Project Phase 2, examining maternal and child health outcomes, community health worker performance, and county health systems strengthening results.",
    tags: ["Evaluation", "Child Health", "Maternal Health", "Kenya"],
    donor: "Save the Children",
  },
  {
    id: "intrahealth-kenya-baseline",
    title: "IntraHealth Human Resources for Health Baseline — 27 Counties",
    client: "IntraHealth International",
    country: "Kenya",
    region: "East Africa",
    year: 2017,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for baseline assessment of human resources for health across 27 Kenyan counties and 12 health worker training institutions, establishing workforce benchmarks for a USAID-funded health systems strengthening programme.",
    tags: ["Baseline", "Health Systems", "USAID", "Kenya"],
    donor: "USAID",
  },
  {
    id: "fhi360-nhpplus-endterm",
    title: "USAID Kenya Nutrition and Health Program Plus End-Term Evaluation",
    client: "FHI360",
    country: "Kenya",
    region: "East Africa",
    year: 2019,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for end-of-term evaluation of the USAID-funded Kenya NHP+, assessing nutrition outcomes, health systems strengthening, and integrated service delivery performance.",
    tags: ["Evaluation", "Nutrition", "Health", "USAID", "Kenya"],
    donor: "USAID",
  },
  {
    id: "kenya-rapid-mte",
    title: "Kenya Resilient Arid Lands Partnership Mid-Term Evaluation",
    client: "Millennium Water Alliance",
    country: "Kenya",
    region: "East Africa",
    year: 2018,
    service: "system-strengthening",
    thematic: "food-security",
    description: "Team Lead for mid-term evaluation of Kenya RAPID across Garissa, Isiolo, Marsabit, Turkana, and Wajir Counties, assessing WASH, livelihoods, and climate resilience outcomes.",
    tags: ["Evaluation", "WASH", "Resilience", "Arid Lands", "Kenya"],
    donor: "Millennium Water Alliance",
  },
  {
    id: "cbm-ophthalmology-impact-eval",
    title: "CBM Ophthalmology Training Scholarship Programme Impact Evaluation",
    client: "CBM Germany",
    country: "Multi-Country (3)",
    region: "East Africa",
    year: 2017,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for impact evaluation of CBM Germany's ophthalmology training scholarship programme (2000–2016) across Kenya, Uganda, and Tanzania, measuring contribution to national eye care systems.",
    tags: ["Impact Evaluation", "Eye Health", "CBM", "East Africa"],
    donor: "CBM Germany",
  },
  {
    id: "amref-maternal-health-nairobi-2017",
    title: "Amref Maternal & Newborn Health Urban Poor End-Term Evaluation",
    client: "Amref Health Africa",
    country: "Kenya",
    region: "East Africa",
    year: 2017,
    service: "system-strengthening",
    thematic: "health",
    description: "Team Lead for end-term evaluation of the Improving Maternal, Newborn, and Child Health Among the Urban Poor project in Nairobi County, assessing coverage, quality of care, and equity of maternal health services.",
    tags: ["Evaluation", "Maternal Health", "Urban Health", "Amref", "Kenya"],
    donor: "Amref Health Africa",
  },
  // ── SAFETY & SECURITY ─────────────────────────────────────────────
  {
    id: "drc-somalia-emergency-2018",
    title: "Danish Refugee Council Somalia Integrated Emergency Response Evaluation",
    client: "Danish Refugee Council",
    country: "Somalia",
    region: "Horn of Africa",
    year: 2018,
    service: "safety-security",
    thematic: "humanitarian",
    description: "Team Lead for evaluation of the Danish Refugee Council's integrated emergency response in Somalia, covering WASH, health, education, disaster risk reduction, and food security programming in conflict-affected communities.",
    tags: ["Evaluation", "Emergency Response", "Humanitarian", "Somalia"],
    donor: "Danish Refugee Council",
  },
  {
    id: "mercy-corps-somalia-education",
    title: "Mercy Corps Somalia School Environment & Education Programme Impact Evaluation",
    client: "Mercy Corps USA",
    country: "Somalia",
    region: "Horn of Africa",
    year: 2017,
    service: "safety-security",
    thematic: "humanitarian",
    description: "Team Member for impact evaluation of Mercy Corps' School Environment and Education Development Programme in Somalia, assessing improvements in education access, WASH infrastructure, and child health outcomes.",
    tags: ["Impact Evaluation", "Education", "WASH", "Humanitarian", "Somalia"],
    donor: "Mercy Corps USA",
  },
  {
    id: "acted-adeso-somalia-study",
    title: "ACTED/ADESO Compounding Chronic Shocks Study — Lower Juba, Somalia",
    client: "ACTED / ADESO",
    country: "Somalia",
    region: "Horn of Africa",
    year: 2017,
    service: "safety-security",
    thematic: "humanitarian",
    description: "Team Lead for empirical study identifying and responding to compounding factors of chronic sequential shocks in Lower Juba, Somalia, informing adaptive humanitarian programming for drought- and conflict-affected communities.",
    tags: ["Research", "Resilience", "Humanitarian", "Somalia", "ACTED"],
    donor: "ACTED / ADESO",
  },
];

export const SERVICE_LABELS: Record<PortfolioProject["service"], string> = {
  "organizational-strengthening": "Organizational Strengthening",
  "capacity-strengthening": "Capacity Strengthening",
  "system-strengthening": "System Strengthening",
  "safety-security": "Safety & Security",
};
